# /RL_PROJECT/docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: ./Backend  # Tells Docker to look in the Backend folder
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    environment:
      - PORT=8000

  frontend:
    build:
      context: ./Frontend # Tells Docker to look in the Frontend folder
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend